{% set name = "sea-names" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sea_names-{{ version }}.tar.gz
  sha256: d0ad91e64b3fb857a2c4681d41cfe589d41fbada94b1cef370d49b7414e6b4fd

build:
  entry_points:
    - sea-names=sea_names.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=42
    - wheel
    - setuptools-scm >=3.4
    - setuptools_scm_git_archive
    - pip
  run:
    - python >=3.8
    - appdirs
    - numpy
    - requests
    - shapely

test:
  imports:
    - sea_names
  commands:
    - pip check
    - sea-names --help
  requires:
    - pip

about:
  home: http://git.axiom/axiom/sea-names
  summary: Determine the sea-name of any arbitrary point or shapely geometry.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - lukecampbell
